---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/items":
    get:
      summary: list items
      responses:
        '200':
          description: successful
    post:
      summary: create item
      responses:
        '200':
          description: successful
  "/api/v1/items/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show item
      responses:
        '200':
          description: successful
    patch:
      summary: update item
      responses:
        '200':
          description: successful
    put:
      summary: update item
      responses:
        '200':
          description: successful
    delete:
      summary: delete item
      responses:
        '200':
          description: successful
  "/api/v1/orders":
    get:
      summary: list orders
      responses:
        '200':
          description: successful
    post:
      summary: create order
      responses:
        '200':
          description: successful
  "/api/v1/orders/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show order
      responses:
        '200':
          description: successful
    patch:
      summary: update order
      responses:
        '200':
          description: successful
    put:
      summary: update order
      responses:
        '200':
          description: successful
    delete:
      summary: delete order
      responses:
        '200':
          description: successful
  "/api/v1/sales":
    get:
      summary: list sales
      responses:
        '200':
          description: successful
    post:
      summary: create sale
      responses:
        '200':
          description: successful
  "/api/v1/sales/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show sale
      responses:
        '200':
          description: successful
    patch:
      summary: update sale
      responses:
        '200':
          description: successful
    put:
      summary: update sale
      responses:
        '200':
          description: successful
    delete:
      summary: delete sale
      responses:
        '200':
          description: successful
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      responses:
        '200':
          description: successful
    put:
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
